import Link from 'next/link';
import { ArrowRight, BadgeCheck, Palette, QrCode, ShieldCheck } from 'lucide-react';

function PhoneMockup(){
  const cards = [
    {name:'Luna Cafe', cls:'green', plan:'8 stamp plan', stamps:'3 / 8', perk:'25% off drink 3', logo:'LC'},
    {name:'Daily Bean', cls:'goldc', plan:'10 stamp plan', stamps:'5 / 10', perk:'25% off drink 5', logo:'DB'},
    {name:'Corner Cup', cls:'rose', plan:'12 stamp plan', stamps:'6 / 12', perk:'25% off drink 6', logo:'CC'},
  ];
  return <div className="phone"><div className="screen"><div className="screen-head"><div><small>Customer mobile view</small><h3>My Brewistan Cards</h3></div><small>Live card preview</small></div>{cards.map((c,i)=><div key={c.name} className={`card ${c.cls}`} data-watermark={c.name}><div className="card-top"><div><small style={{color:'rgba(255,255,255,.68)'}}>Custom brand preview</small><h3>{c.name}</h3></div><div className="sample-logo">{c.logo}</div></div><div className="dots">{Array.from({length:i===0?8:i===1?10:12}).map((_,idx)=><span key={idx} className={`dot ${idx < (i===0?3:i===1?5:6)?'on':''}`}/>)}</div><div className="card-meta"><span>{c.stamps}</span><span>{c.plan}</span></div><div className="card-meta"><span>Perk</span><span>{c.perk}</span></div><small style={{position:'absolute',left:18,bottom:10,color:'rgba(255,255,255,.66)'}}>Created by Brewistan.com</small></div>)}</div></div>
}

export default function Home(){
 return <main>
  <header className="container nav"><Link href="/" className="brand"><span className="mark">B</span>Brewistan</Link><nav className="navlinks"><a className="pill" href="#features">Features</a><a className="pill" href="#daily">Daily use</a><Link className="pill" href="/get-started">Cafe sign in</Link><Link className="btn" href="/get-started">Get started <ArrowRight size={16}/></Link></nav></header>
  <section className="container hero"><div><div className="eyebrow">Built for modern cafés in Iraq</div><h1 className="h1">A premium loyalty website your customers can use in seconds.</h1><p className="lead">Brewistan helps cafés replace paper cards with a branded mobile loyalty experience. Customers scan your QR, collect stamps, unlock rewards, and come back more often.</p><div className="actions"><Link className="btn" href="/get-started">Create café account <ArrowRight size={16}/></Link><a className="btn secondary" href="#daily">See how it works</a></div><div className="feature-row"><div className="mini"><strong>5 minutes setup</strong><span>Create café, branch, campaign, and QR.</span></div><div className="mini"><strong>Custom cards</strong><span>Logo, colors, opacity, and watermark.</span></div><div className="mini"><strong>Custom campaigns</strong><span>8, 10, 12, or custom stamp plans.</span></div><div className="mini"><strong>Staff approval</strong><span>Barista approves stamp requests from phone.</span></div></div></div><div className="phone-wrap"><PhoneMockup/></div></section>
  <section id="features" className="container section"><div className="eyebrow">Core features</div><h2>Everything a café needs to start loyalty without installing an app.</h2><div className="grid3"><div className="panel"><div className="icon"><Palette/></div><h3>Luxury branded cards</h3><p>Each café can choose card colors, transparency, logo, and a highlighted watermark with the café name.</p></div><div className="panel"><div className="icon"><QrCode/></div><h3>QR-first workflow</h3><p>Place one QR near the cashier. Customers scan it, request a stamp, and staff approve from their phone.</p></div><div className="panel"><div className="icon"><ShieldCheck/></div><h3>Controlled staff access</h3><p>Add baristas and branch managers with clear permission levels, so daily operations stay safe and organized.</p></div></div></section>
  <section id="daily" className="container section"><div className="eyebrow">Daily café flow</div><h2>Designed for real cashier counters, not complicated software.</h2><div className="grid3"><div className="panel"><h3>1. Customer scans</h3><p>The QR opens Brewistan on mobile. New customers create an account; returning customers continue with their existing cards.</p></div><div className="panel"><h3>2. Customer requests stamp</h3><p>After ordering, the customer taps request stamp. The request appears instantly on the barista approval screen.</p></div><div className="panel"><h3>3. Barista approves</h3><p>The barista checks the order, approves the request, and the customer’s card updates with the new stamp and reward progress.</p></div></div></section>
  <footer className="container footer">© Brewistan.com — premium web-based loyalty for cafés.</footer>
 </main>
}
